name: pleb_ln
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
    
  # State Management (updated to latest version)
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  
  # Existing dependencies (updated to latest versions)
  money_formatter: ^0.0.6
  qr_flutter: ^4.1.0
  tuple: ^2.0.2
  flutter_secure_storage: ^9.2.2
  mobile_scanner: ^5.2.3
  rename: ^3.0.2
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  http: ^1.2.2
  intl: ^0.19.0
  font_awesome_flutter: ^10.7.0
  numberpicker: ^2.1.2
  google_fonts: ^6.2.1
  page_transition: ^2.1.0
  convert: ^3.1.1
  percent_indicator: ^4.2.3
  http_plus: ^0.2.3
  protobuf: ^3.1.0
  grpc: ^4.0.1
  fixnum: ^1.1.1
  curved_navigation_bar: ^1.0.6
  progress_state_button: ^1.0.4
  dropdown_button2: ^2.3.9
  carousel_slider: ^5.0.0
  carousel_indicator: ^1.0.6
  lottie: ^3.1.2
  # Removed coingecko_api due to dependency conflicts
  # Will use direct HTTP calls instead
  
  # New modern dependencies (updated to latest)
  dio: ^5.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  crypto: ^3.0.5
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  go_router: ^14.6.1
  url_launcher: ^6.3.1
  share_plus: ^10.1.2
  clipboard: ^0.1.3
  # Removed device_info_plus and package_info_plus due to web dependency conflicts
  # Will implement platform-specific solutions
  connectivity_plus: ^6.0.5
  local_auth: ^2.3.0
  image: ^4.2.0
  path_provider: ^2.1.4
  path: ^1.9.0
  flutter_native_splash: ^2.4.1
  equatable: ^2.0.5
  collection: ^1.18.0
  freezed_annotation: ^2.4.4

# Force newer versions of packages that don't support latest AGP
dependency_overrides:
  flutter_plugin_android_lifecycle: ^2.0.28
  
flutter_native_splash:
  color: "#000000"
  image: "images/Pleb-logos_white.png"
  android: true
  ios: false

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  
  # Code generation (updated to latest)
  freezed: ^2.5.7
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  
  # Linting (updated to latest)
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/Pleb-black_backdrop.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "images/Pleb-logos_white.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/Pleb-logos_black.png
    - images/Pleb-logos_transparent.png
    - images/Pleb-logos_white.png
    - images/Pleb-logos.jpeg
    - images/Pleb-logos_round.png
    - animations/blue-checkmark.json
    - images/Pleb-black_backdrop.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages